const enums = {
    INSTANT: 'instant',
    PAYSTACK: 'paystack',
    RAVE: 'rave',
    DEBIT: 0,
    CREDIT: 1,
    BANK: 'bank',
    CARD: 'card',
    NUBAN: 'nuban',
    PAID: 'paid',
    INITIATED: 'initiated',
    BALANCE: 'balance',
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    NIGERIA: 'NG',
    ACCOUNT: 'account',
    VERIFIED: 'verified',
    SUBMITTED: 'submitted',
    REJECTED: 'rejected',
    NOKYC: 'nokyc',
    MAXFUNDRAVE: 500000,
    MAXFUNDPAYSTACK: 500000,
    MALE: 0,
    FEMALE: 1,
    OTHERS: 2,
    USERCLAIMS: ['currency', 'service'],
    SUGGESTED_AUTH: 'PIN',
    CLOUDINARY: 'cloudinary',
    PROVIDER: ['facebook', 'twitter', 'instagram', 'email'],
    FACEBOOK: 'facebook',
    TWITTER: 'twitter',
    INSTAGRAM: 'instagram',
    GOOGLE: 'google'
};

module.exports = enums;